# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: StrathSEDS

# Short description (goes below the title; it will also be used in the RSS feed)
description: Students for the Exploration and Development of Space

# Your name, as you want it to appear underneath each post and in the footer
author: StrathSED

# Logo image
logo: //www.strathseds.org/static/images/logos/strathseds-200px.png

# Your email if you want it to be linked on the contact page
contact_email: contact@strathseds.org
web_email: webmaster@strathseds.org

# Are we in freshers fair mode?
freshers: 0

# It's XMAS!
xmas: 1

# Committee data
committee_positions: [president, vp1, vp2, treasurer, cto, outreach, social]
committee:
  president:
    name: Ben Turner
    gravatar: 29e309f15dc5748a962f13185d90bf62
    email: president@strathseds.org
    position: President
  vp1:
    name: Jennifer Miller
    gravatar: 29e309f15dc5748a962f13185d90bf62
    email: vicepresident@strathseds.org
    position: Vice-president
  vp2:
    name: Liam Quinn 
    gravatar: 29e309f15dc5748a962f13185d90bf62
    email: vicepresident@strathseds.org
    position: Vice-president
  treasurer:
    name: Ciara McGrath
    gravatar: 29e309f15dc5748a962f13185d90bf62
    email: treasurer@strathseds.org
    position: Treasurer
  cto:
    name: Adam McGhie
    gravatar: 29e309f15dc5748a962f13185d90bf62
    email: cto@strathseds.org
    position: Chief Technology Officer
  outreach:
    name: Lukaz Zapotoczny
    gravatar: 29e309f15dc5748a962f13185d90bf62
    email: contact@strathseds.org
    position: Outreach Coordinator
  social:
    name: Ryan Ross
    gravatar: 29e309f15dc5748a962f13185d90bf62
    email: contact@strathseds.org
    position: Social Coordinator
  

  

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
baseurl: //www.strathseds.org
url: //www.strathseds.org/
projecturl: //www.strathseds.org/projects/

# Static URL's
staticurl: //www.strathseds.org/static
imageurl: //www.strathseds.org/static/images/

# Link to the strathseds google doc
joinlink: https://docs.google.com/forms/d/1se_VAeEZ0Coy9uWl6fSnfEhbLANFqqCxk_F3Ye6W_CM/viewform?embedded=true

# Google analytics id
analyticsID: UA-39702307-1
analyticsDomain: strathseds.org

twitter_name: 'StrathSEDS'
twitter_creator: '@StrathSEDS'
twitter_title: Students for the Exploration and Development of Space
twitter_description: The Strathclyde Students for the Exploration and Development of Space is an engineering/science based society for students of the University of Strathclyde.
twitter_domain: strathseds.org

facebook_page_name: StrathSEDS

# Misc
future: false

#### Under the Hood Stuff #####

# Use rdiscount as the markdown engine because it generates html5 compliant code for stuff like footnotes
# If you use maroku (default engine) some of your generated pages may not validate or lint as html5
# If you don't have it install it via gem install rdiscount
markdown: rdiscount

# Continue compiling even if there are errors. Keep it true, unless troubleshooting.
auto: true

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: README.md, package.json, grunt.js, Gruntfile.js, node_modules, gen.sh, Gemfile
