# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: StrathSEDS

# Short description (goes below the title; it will also be used in the RSS feed)
description: Students for the Exploration and Development of Space

# Your name, as you want it to appear underneath each post and in the footer
author: StrathSED

# Your email if you want it to be linked on the contact page
author_email: strathseds@hotmail.com

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://www.strathseds.org/
baseurl: http://www.strathseds.org
projecturl: http://www.strathseds.org/projects/

# Static URL's
staticurl: http://static.strathseds.org
socialiconpath: http://static.strathseds.org/images/icons/
imageurl: http://static.strathseds.org/images/

# Link to the strathseds google doc
joinlink: https://docs.google.com/forms/d/1se_VAeEZ0Coy9uWl6fSnfEhbLANFqqCxk_F3Ye6W_CM/viewform?embedded=true

# Google analytics id
analyticsID: UA-39702307-1
analyticsDomain: strathseds.org

#### Under the Hood Stuff #####

# Use rdiscount as the markdown engine because it generates html5 compliant code for stuff like footnotes
# If you use maroku (default engine) some of your generated pages may not validate or lint as html5
# If you don't have it install it via gem install rdiscount
markdown: rdiscount

# Continue compiling even if there are errors. Keep it true, unless troubleshooting.
auto: true

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: README.md, package.json, grunt.js, Gruntfile.js, node_modules 
